CC = gcc
SOURCES = $(wildcard src/dtk/*.c) src/main.c
CFLAGS = -DSIMULATOR -DSINGLE_THREADED -DHACK_ALERT -DFULL_LANGUAGE_SUPPORT -DFULL_LTS -DNO_INDEXES -DDIRECT_LTS_INPUT -DACNA -DHOMOGRAPHS -DMATH_MODE -DDIVIDED_LTS_RULES -DOUTPUT_FILE -Wl,-Bstatic -Wl,-Bdynamic -I include -w -g -DMultiple_Sample_Rates
OBJECTS = $(SOURCES:.c=.o)
TARGET = out/main

$(TARGET) : $(OBJECTS)
	$(CC) ${DEFINES} ${CFLAGS} -o $@ $^
